# Generated by Django 5.2.4 on 2025-08-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='driver',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('yangi', '🆕 Yangi'), ('jonatilgan', '📦 Jo‘natilgan'), ('yetkazildi', '✅ Yetkazildi')], default='yangi', max_length=20),
        ),
    ]
