# Generated by Django 5.2.4 on 2025-08-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_order_driver_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='role',
            field=models.CharField(choices=[('mijoz', '🧑 Mijoz'), ('admin', '🛠 Admin'), ('haydovchi', '🚚 Haydovchi')], default='mijoz', max_length=20),
        ),
    ]
