# Generated by Django 5.2.4 on 2025-08-01 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_telegramuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'haydovchi'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_orders', to='app.telegramuser'),
        ),
    ]
