# Generated by Django 5.2.4 on 2025-08-05 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_order_latitude_order_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'haydovchi'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_products', to='app.telegramuser', verbose_name='Defolt haydovchi'),
        ),
    ]
