# Generated by Django 5.2.4 on 2025-08-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_product_default_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
