# Generated by Django 5.2.4 on 2025-08-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_telegramuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='avatar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
