# Generated by Django 5.2.4 on 2025-08-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_telegramuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
